add_test([=[GoogleTestCi.Foo]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=GoogleTestCi.Foo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GoogleTestCi.Foo]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ExampleTest.DmitriiLeonidovich]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=ExampleTest.DmitriiLeonidovich]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ExampleTest.DmitriiLeonidovich]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.exact_symbol]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.exact_symbol]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.exact_symbol]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.resize_char]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.resize_char]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.resize_char]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.resize_int]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.resize_int]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.resize_int]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.swap]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.swap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.swap]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.reserve]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.reserve]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.reserve]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.reserve_more]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.reserve_more]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.reserve_more]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.iterator]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.iterator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.iterator]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.symbol_input]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.symbol_input]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.symbol_input]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.symbol_back]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.symbol_back]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.symbol_back]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_equal_char]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_equal_char]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_equal_char]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_equal_int]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_equal_int]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_equal_int]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_not_equal]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_not_equal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_not_equal]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_more_not_equal]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_more_not_equal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_more_not_equal]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_not_equal_int]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_not_equal_int]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_not_equal_int]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_less]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_less]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_less]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_more]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_more]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_more]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_bigger]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_bigger]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_bigger]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_less_size]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_less_size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_less_size]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_much_less_size]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_much_less_size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_much_less_size]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_not_more]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_not_more]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_not_more]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_not_less]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_not_less]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_not_less]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.operator_much_bigger]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.operator_much_bigger]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.operator_much_bigger]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vector.empty]=]  [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild/example_tests]==] [==[--gtest_filter=Vector.empty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vector.empty]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/stanislav/Documents/Учеба/ершов/vektor/mybuild]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  example_tests_TESTS GoogleTestCi.Foo ExampleTest.DmitriiLeonidovich Vector.exact_symbol Vector.resize_char Vector.resize_int Vector.swap Vector.reserve Vector.reserve_more Vector.iterator Vector.symbol_input Vector.symbol_back Vector.operator_equal_char Vector.operator_equal_int Vector.operator_not_equal Vector.operator_more_not_equal Vector.operator_not_equal_int Vector.operator_less Vector.operator_more Vector.operator_bigger Vector.operator_less_size Vector.operator_much_less_size Vector.operator_not_more Vector.operator_not_less Vector.operator_much_bigger Vector.empty)
